name: login
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.16.0
  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.13.5
  font_awesome_flutter: ^8.8.1
  image_picker: ^0.6.5+3
  google_sign_in:
  flutter_bloc:
  equatable:
  meta:
  dynamic_list_view: ^0.1.5
  google_maps_flutter: ^0.5.27+3
  easy_localization: ^2.3.2
  location: ^3.0.2
  flip_card: 0.4.4
  shimmer: ^1.1.0
  flutter_slidable: ^0.5.4
  flutter_dialogflow: ^0.1.3
  bubble: ^1.1.9+1


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets: 
    - assets/logoU.png
    - assets/images/socloselogo.PNG
    - assets/images/point.png
    - assets/images/person1.jpg
    - assets/images/person2.png
    - assets/images/person3.jpg
    - assets/images/person4.png
    - assets/images/person5.jpg
    - assets/images/person6.jpg
    - assets/images/person7.jpg
    - assets/images/chat-background-1.jpg
    - assets/soclose-eddfe-4f18ed7a3f54.json
 